plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.7'
}

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name = "placeholderapi"
        url = "https://repo.extendedclip.com/releases/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.20-R0.1-SNAPSHOT")
    compileOnly("me.clip:placeholderapi:2.11.6")

    implementation("io.agroal:agroal-api:3.2.1") // Agroal (29.08.26)
    implementation("io.agroal:agroal-pool:3.2.1")



    implementation("org.xerial:sqlite-jdbc:3.53.2.1") // SQLite (16.08.26)
    implementation("com.mysql:mysql-connector-j:26.7.0") // MySQL (16.08.26)
    implementation("org.postgresql:postgresql:42.7.13") // PostgreSQL (21.08.26)
}

shadowJar {
    relocate("io.agroal", "libs.agroal")
    relocate("org.xerial", "libs.sqlite")
    relocate("com.mysql", "libs.mysql")
    relocate("org.postgresql", "libs.postgresql")

    getDestinationDirectory().set(new File("D:\\Minecraft\\Servers\\Paper 1.20.1\\plugins\\"))
    archiveFileName = "NaturalTracker-${project.version}.jar"
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion)
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

tasks.register('runServer', Exec) {
    dependsOn 'shadowJar'

    group = 'application'
    description = 'Собирает плагин и запускает тестовый сервер'

    def serverDir = file('D:/Minecraft/Servers/Paper 1.20.1')
    def serverJarName = 'paper-1.20.1-196.jar'

    workingDir = serverDir

    def jvmArgs = [
            '-Xms4G', // Увеличил до 4G для стабильности с базами данных
            '-Xmx4G',
            '-XX:+UseG1GC', '-XX:+ParallelRefProcEnabled', '-XX:MaxGCPauseMillis=200',
            '-XX:+UnlockExperimentalVMOptions', '-XX:+DisableExplicitGC', '-XX:+AlwaysPreTouch',
            '-XX:G1NewSizePercent=40', '-XX:G1MaxNewSizePercent=50', '-XX:G1HeapRegionSize=16M',
            '-XX:G1ReservePercent=15', '-XX:G1HeapWastePercent=5', '-XX:G1MixedGCCountTarget=4',
            '-XX:InitiatingHeapOccupancyPercent=20', '-XX:G1MixedGCLiveThresholdPercent=90',
            '-XX:G1RSetUpdatingPauseTimePercent=5', '-XX:SurvivorRatio=32', '-XX:+PerfDisableSharedMem',
            '-XX:MaxTenuringThreshold=1', '-Dusing.aikars.flags=https://mcflags.emc.gs',
            '--add-modules=jdk.incubator.vector', '-Daikars.new.flags=true'
    ]

    commandLine = ['cmd', '/c', 'start', '"Minecraft Server"', 'java'] + jvmArgs + ['-jar', serverJarName, '-nogui']
}